# base
random_seed: 0
save_path: save/
no_cuda: False
gpus: -1
parameters_config_path: config/parameters.yaml

# data_preparation
batch_size: 32
val_size: 0.2
num_workers: 0
transform_config_path: config/transform.yaml
max_files: null

# train
val_iter: null
lr: 1e-3
train_iter: 100
lr_scheduler: CosineAnnealingLR
step_size: 10
gamma: 0.1
precision: 32
profiler: null
weights_summary: null

# model
in_chans: 3
checkpoint_path: null
optimizer_config_path: config/optimizer.yaml

# evaluate
n_splits: 5

# tune
tune_iter: 100
tune_cpu: 1
tune_gpu: null
hyperparameter_config_path: config/hyperparameter.yaml
tune_debug: False
